version: "3.6"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: root
    volumes:
      - type: volume
        source: postgres
        target: /var/lib/postgresql/data

  app:
    image: node:17-alpine
    working_dir: "/app"
    user: node
    command: "yarn dev -c /app/config.dev.json"
    volumes:
      - type: bind
        source: ./
        target: /app
      - type: bind
        source: ./data
        target: /data
    ports:
      - 0.0.0.0:10016:10016
    environment:
      DATABASE_URL: postgresql://root:password@postgres/dag?connect_timeout=300&pool_timeout=300

volumes:
  postgres: {}
